
import:
- AdaE
- complex
- multi_lookup_embedder
complex:
  entity_embedder:
    type: multi_lookup_embedder
    dropout: 0.5
    regularize_weight: 1.3408200403806817e-08
    # pretrain:
    #   model_filename: '/home/guanzp/code/AdaE/kge/local/fb15k-237/experiments/20240103-171738-complex-512-reciprocal_relations_model--ed-0.5--rd-0.4-best/checkpoint_best.pt'
  relation_embedder:
    type: multi_lookup_embedder
    dropout: 0.4
    regularize_weight: 1.0e-12
    # pretrain:
    #   model_filename: '/home/guanzp/code/AdaE/kge/local/fb15k-237/experiments/20240103-171738-complex-512-reciprocal_relations_model--ed-0.5--rd-0.4-best/checkpoint_best.pt'
dataset:
  name: fb15k-237
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
  trace_level: example

multi_lookup_embedder:
  dim: 20
  initialize: uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.5592429029559286
    uniform_:
      a: -0.8328168489829233
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 3
    weighted: true
model: AdaE

negative_sampling:
  implementation: batch
  num_samples:
    o: 1000
    p: -1
    s: 529

AdaE:
  base_model:
    type: complex
train:
  auto_correct: true
  batch_size: 1024
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 7
    threshold: 0.0001
  max_epochs: 200
  optimizer_args:
    lr: 0.25
  type: darts
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05
    patience: 30
  every: 5
job.device:
  cuda:0
AdaE_config:
  adae: True
  bi-level: False
  share: True
  type: '1vsall'
  ali_way: 'zp'
  # train_mode: ['rank','auto','fix','original']
  train_mode: 'auto'
  dim_list: [128,512]
  cie: True
  choice_list: [-1]
  s_u: 4
  ratio: 0.8
  urolled: False
  t_s: 256
  lr_p: 0.1
  device: 'cuda:0'
  folder: None
  #目前device没用