import:
- complex
- AdaE
- multi_lookup_embedder
complex:
  entity_embedder:
    type: multi_lookup_embedder
    dropout: 0.1
    regularize_weight: 1.0274165130442088e-15
    pretrain:
      model_filename: "/data1/gzp/local/yago3-10/experiments/20240102-223259-complex-512-complex--ed-0.1--rd-0.2-best/checkpoint_best.pt"
  relation_embedder:
    type: multi_lookup_embedder
    dropout: 0.2
    regularize_weight: 2.934669571854759e-10
    pretrain:
      model_filename: "/data1/gzp/local/yago3-10/experiments/20240102-223259-complex-512-complex--ed-0.1--rd-0.2-best/checkpoint_best.pt"
dataset:
  files:
    test:
      size: 5000
    test_without_unseen:
      filename: test_without_unseen.del
      size: 4982
      type: triples
    train:
      size: 1079040
    train_sample:
      filename: train_sample.del
      size: 5000
      type: triples
    valid:
      size: 5000
    valid_without_unseen:
      filename: valid_without_unseen.del
      size: 4978
      type: triples
  name: yago3-10
  num_entities: 123182
  num_relations: 37
eval:
  batch_size: 256
  chunk_size: 25000
  metrics_per:
    relation_type: true
  trace_level: example

multi_lookup_embedder:
  dim: 192
  initialize: uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.036423597922559676
    uniform_:
      a: -0.4357536096219625
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 3
    weighted: true
  sparse: true
model: AdaE
negative_sampling:
  implementation: batch
  num_samples:
    o: 8942
    s: 8919
  shared: true
  with_replacement: false
AdaE:
  base_model:
    type: complex
train:
  auto_correct: true
  batch_size: 1024
  loss_arg: 1.0
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 5
    threshold: 0.0001
  max_epochs: 200
  optimizer_args:
    lr: 0.26
  type: darts
valid:
  early_stopping:
    min_threshold:
      epochs: 10
      metric_value: 0.1
    patience: 10

job:
  device: cuda:7
AdaE_config:
  adae: True
  bi-level: False
  share: True
  type: '1vsall'
  ali_way: 'zp'
  cie: True
  # train_mode: ['rank','auto','fix','original']
  train_mode: 'auto'
  dim_list: [128,192]
  choice_list: [0.5]
  s_u: 2
  ratio: 0.5
  urolled: False
  t_s: 128
  lr_p: 0.1825
  device: 'cuda:3'
  #目前device没用
  